#! /bin/sh
xinput set-prop 16 307 1 1
wal -R
sxhkd &
pulseaudio &
start-dunst &
# feh --bg-fill ~/.wallpapers/void.jpg
xrdb -merge ~/.Xresources
panel &

compton -bcCG --shadow-exclude '!focused' --no-fading-openclose

bspc monitor -d      

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true

bspc rule -a Pinentry state=floating
