#! /bin/sh
xinput set-prop 16 307 1 1
wal -R
sxhkd &
pulseaudio &
start-dunst &
# feh --bg-fill ~/.wallpapers/void.jpg
xrdb -merge ~/.Xresources
panel_desktops &
panel_center &
panel_top_right &
panel_warning &

twmnd light &
twmnd sound &
#twmnd notifications &

compton -bcCG --shadow-exclude '!focused' --no-fading-openclose

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


bspc monitor eDP1 -d      
bspc monitor HDMI2 -d VII VIII IX X


bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus true

bspc rule -a Pinentry state=floating
