# Shell variables
# Generated by 'wal'
wallpaper='/home/patrik/.wallpapers/city.jpg'

# Special
background='#0B2025'
foreground='#c8c6c4'
cursor='#c8c6c4'

# Colors
color0='#0B2025'
color1='#A06A40'
color2='#7D807F'
color3='#C79163'
color4='#087687'
color5='#527C84'
color6='#508A96'
color7='#c8c6c4'
color8='#8c8a89'
color9='#A06A40'
color10='#7D807F'
color11='#C79163'
color12='#087687'
color13='#527C84'
color14='#508A96'
color15='#c8c6c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
